### ISSUE TITLE
[FEAT]web interface

### ISSUE THREAD

**Issue by kaddirov** [leplusorg/docker-pdf#17]
**Which tool would you like to see added to the image? Why is it useful?**
A clear and concise description of what the tool is and what it is used for. Ex. If I had tool X I could [...]. Please also provide a example of the command-line that you would like to run.

**How is it installed? Does it require any configuration?**
A clear and concise description of how the tool is installed. Ideally using a package manager (apt, pip, npm...) to keep the image automatically up to date with the latest version of the tool.

**Comment by thomasleplus** [comment]
Having a web interface would be nice but I am afraid that I don't have the sufficient skills to make one myself. Maybe someone else will pick up this request.
